config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'

  devise_for :users
  resources :contacts, only: [:create]

  authenticate :user do
    namespace :users do
      root to: 'dashboard#index'
      get '/about', to: 'dashboard#about'
      get '/tasks', to: 'tasks#about'
    end
  end

  authenticate :admin do
    namespace :admins do
      root to: 'dashboard#index'
      get '/about', to: 'dashboard#about'
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    'Administrador'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
end

app/controllers/admins/base_controller.rb
class Admins::BaseController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'admins/layouts/application'
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < Admins::BaseController
 
  def index
  end

  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def layout_by_resource
    if devise_controller?
      if resource_name == :user && ["edit", "update"].include?(action_name)
        "users/layouts/application"
      elsif resource_name == :admin
        "admins/layouts/application"
      else
        "layouts/session"
      end
    else
      "layouts/application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  protected  
    def after_sign_in_path_for(resource)
      return admins_root_path if resource.is_a? Admin  
      
      users_root_path
    end

    def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
        new_user_session_path
      elsif resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_parms)

    if @contact.save
      flash[:success] = "Mensagem enviada com sucesso!"
      #redirect_to root_path
      @contact = Contact.new
    else
      flash[:error] = "Existem dados incorretos! Por favor verifique."
      #render "home/index"
    end

  end

  private
  def contact_parms
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact = Contact.new
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'users/layouts/application'
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::BaseController
 
  def index
  end

  def about
  end
end

app/controllers/users/tasks_controller.rb
class Users::TasksController < Users::BaseController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
      notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def full_title(page_title = '', base_title = 'Bucketlist')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/dashboard/about.html.erb
<h1>About do admin</h1>

app/views/admins/dashboard/index.html.erb
<h1>Dashboard do admin</h1>

app/views/admins/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-gray">
  
  <%= link_to "Bucketlist", root_path, class: "nav-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Página Inicial</a>
      </li>

      <% if admin_signed_in? %>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <%= current_admin.name %> 
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Sair', destroy_admin_session_path, method: :delete,
                               class: 'dropdown-item' %>
           </div>
         </li>
      <% else %>
        <li class="nav-item">
           <%= link_to 'Entrar', new_admin_session_path,
                                 class: 'btn btn-primary btn-sm' %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/admins/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Home</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'admins/application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admins/application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>
  <body>

    <%= render 'admins/layouts/navbar' %>

    <div class="container">
    	<%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/home/_contact_form.html.erb
<div id="flash_messages"></div>

<%= simple_form_for(@contact, remote: true) do |f| %>
   <div class="form-inputs">
     <%= f.input :name %>
     <%= f.input :email %>
     <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enviar", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/home/index.html.erb
<section>
  <article class="card mb-5 text-center">
    <div class="card-body">	
      <header class="card-title">
        <h1>Bucketlist</h1>	
      </header>

      <p class="card-text">
        É a maneira mais fácil de fazer as coisas. Se você está planejando um
        feriado, compartilhando uma lista de compras com um parceiro ou
        gerenciando vários projetos de trabalho, o Wunderlist está aqui para
        ajudá-lo a marcar seus itens pessoais e profissionais.
      </p>
    </div>
  </article>

  <article class="card mb-5 text-center">
    <div class="card-body">
      <header class="card-title">
        <h2>O que preciso fazer agora?</h2>	
      </header>

      <p class="card-text">
        Se você faz essa pergunta com uma certa frequência, este é o aplicativo
        ideal para você
      </p>

      <a href="#" class="btn btn-primary"> Registre-se agora mesmo!</a>
    </div>
  </article>

  <article class="card mb-5">
    <div class="card-body">
      <header class="card-title">
        <h2>Fale conosco</h2>	
      </header>

      <div id="contact_form">
        <%= render 'home/contact_form'%>
      </div>
    </div>
  </article>


</section>

app/views/layouts/_footer.html.erb
<footer class="footer bg-light">
	<div class="container text-center">
		<span class="text-muted">Created by Diego Marczal to WD5 cours - Copyright 2017 ©</span>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <%= link_to "Bucketlist", root_path, class: "nav-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Página Inicial</a>
      </li>

      <% if user_signed_in? %>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <%= current_user.name %> 
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <%= link_to 'Meu perfil', edit_user_registration_path,
                                     class: 'dropdown-item' %>
             <%= link_to 'Sair', destroy_user_session_path, method: :delete,
                               class: 'dropdown-item' %>
           </div>
         </li>
      <% else %>
        <li class="nav-item">
           <%= link_to 'Entrar', new_user_session_path,
                                 class: 'btn btn-primary btn-sm' %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Home</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>
  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
    	<%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= full_title(yield(:head_title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'session', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'session', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>
  <body>

		<div id="<%= controller_name %>-<%= action_name %>" class="container">
			<div class="vertical-centering horizontal-centering">
				<%= render 'shared/flash_messages' %>

				<div>
					<h3 class="text-center gray-text2"><%= yield :title %></h3>
					<p class="gray-text2"><%= yield :sub_title %></p>
				</div>

				<%= yield %>

			</div> <!-- .vertical-centering .horizontal-centering -->
		</div> <!-- #home-index -->

  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
    <button class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/users/dashboard/about.html.erb
<h1>Dashboard do usuário</h1>

app/views/users/dashboard/index.html.erb
<h1>Dashboard do usuário</h1>

app/views/users/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-gray">
  
  <%= link_to "Bucketlist", root_path, class: "nav-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Página Inicial</a>
      </li>

      <% if user_signed_in? %>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <%= current_user.name %> 
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <%= link_to 'Meu perfil', edit_user_registration_path,
                                     class: 'dropdown-item' %>
             <%= link_to 'Sair', destroy_user_session_path, method: :delete,
                               class: 'dropdown-item' %>
           </div>
         </li>
      <% else %>
        <li class="nav-item">
           <%= link_to 'Entrar', new_user_session_path,
                                 class: 'btn btn-primary btn-sm' %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/users/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Home</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'users/application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'users/application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>
  <body>

    <%= render 'users/layouts/navbar' %>

    <div class="container">
    	<%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/tasks/about.html.erb
<h1>Dashboard do usuário</h1>

app/views/users/tasks/index.html.erb
<h1>Tasks do usuário</h1>